language: cpp

sudo: required

branches:
    only:
      - master
      
compiler: gcc

os: linux
addons:
  apt:
    soures:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      
script:
  - export PC=gpc-7
  - export CX=g++-7
